-- Banco complementar do Show da Bíblia: 30 questões inéditas.
-- Revisado contra os dois arquivos-base enviados: não há enunciados repetidos.
-- Distribuição: 10 fáceis, 10 médias e 10 difíceis; 15 AT e 15 NT.
-- Cada questão possui quatro alternativas e traduções em pt-BR, en e es.

CREATE TEMP TABLE biblical_question_seed_part_3 (
  question_id uuid PRIMARY KEY,
  difficulty_level smallint NOT NULL,
  category_id uuid NOT NULL,
  pt_statement text NOT NULL,
  en_statement text NOT NULL,
  es_statement text NOT NULL,
  pt_explanation text NOT NULL,
  en_explanation text NOT NULL,
  es_explanation text NOT NULL,
  pt_options text[] NOT NULL,
  en_options text[] NOT NULL,
  es_options text[] NOT NULL,
  correct_position smallint NOT NULL,
  CONSTRAINT biblical_question_seed_part_3_difficulty_valid
    CHECK (difficulty_level BETWEEN 1 AND 3),
  CONSTRAINT biblical_question_seed_part_3_correct_position_valid
    CHECK (correct_position BETWEEN 1 AND 4),
  CONSTRAINT biblical_question_seed_part_3_options_count_valid
    CHECK (
      cardinality(pt_options) = 4
      AND cardinality(en_options) = 4
      AND cardinality(es_options) = 4
    ),
  CONSTRAINT biblical_question_seed_part_3_texts_not_blank
    CHECK (
      btrim(pt_statement) <> ''
      AND btrim(en_statement) <> ''
      AND btrim(es_statement) <> ''
      AND btrim(pt_explanation) <> ''
      AND btrim(en_explanation) <> ''
      AND btrim(es_explanation) <> ''
    )
) ON COMMIT DROP;

INSERT INTO biblical_question_seed_part_3 VALUES
-- Nível 1 — Antigo Testamento
('019f9752-0001-7000-8000-000000000046', 1, '019f9749-7a00-7000-8000-000000000001', 'Quem sou eu? Fui sogro de Moisés e sacerdote de Midiã.', 'Who am I? I was Moses'' father-in-law and the priest of Midian.', '¿Quién soy? Fui el suegro de Moisés y sacerdote de Madián.', 'Jetro era sogro de Moisés e sacerdote de Midiã. Referência: Êxodo 3:1; 18:1.', 'Jethro was Moses'' father-in-law and the priest of Midian. Reference: Exodus 3:1; 18:1.', 'Jetró era el suegro de Moisés y sacerdote de Madián. Referencia: Éxodo 3:1; 18:1.', ARRAY['Jetro','Hur','Eli','Balaão'], ARRAY['Jethro','Hur','Eli','Balaam'], ARRAY['Jetró','Hur','Elí','Balaam'], 1),
('019f9752-0001-7000-8000-000000000047', 1, '019f9749-7a00-7000-8000-000000000001', 'Que alimento Deus forneceu aos israelitas no deserto?', 'What food did God provide for the Israelites in the wilderness?', '¿Qué alimento proporcionó Dios a los israelitas en el desierto?', 'Deus deu o maná ao povo de Israel durante sua caminhada no deserto. Referência: Êxodo 16:14–15.', 'God gave manna to the people of Israel during their journey in the wilderness. Reference: Exodus 16:14–15.', 'Dios dio maná al pueblo de Israel durante su camino por el desierto. Referencia: Éxodo 16:14–15.', ARRAY['Maná','Uvas','Peixes','Trigo'], ARRAY['Manna','Grapes','Fish','Wheat'], ARRAY['Maná','Uvas','Peces','Trigo'], 1),
('019f9752-0001-7000-8000-000000000048', 1, '019f9749-7a00-7000-8000-000000000001', 'Quem sou eu? Fui mãe de Ismael, filho de Abraão.', 'Who am I? I was the mother of Ishmael, Abraham''s son.', '¿Quién soy? Fui la madre de Ismael, hijo de Abraham.', 'Agar deu à luz Ismael, filho de Abraão. Referência: Gênesis 16:15.', 'Hagar gave birth to Ishmael, Abraham''s son. Reference: Genesis 16:15.', 'Agar dio a luz a Ismael, hijo de Abraham. Referencia: Génesis 16:15.', ARRAY['Agar','Sara','Rebeca','Raquel'], ARRAY['Hagar','Sarah','Rebekah','Rachel'], ARRAY['Agar','Sara','Rebeca','Raquel'], 1),
('019f9752-0001-7000-8000-000000000049', 1, '019f9749-7a00-7000-8000-000000000001', 'Qual juíza e profetisa julgava Israel debaixo de uma palmeira?', 'Which judge and prophetess judged Israel under a palm tree?', '¿Qué jueza y profetisa juzgaba a Israel debajo de una palmera?', 'Débora era profetisa e julgava Israel debaixo da palmeira de Débora. Referência: Juízes 4:4–5.', 'Deborah was a prophetess and judged Israel under the palm tree of Deborah. Reference: Judges 4:4–5.', 'Débora era profetisa y juzgaba a Israel debajo de la palmera de Débora. Referencia: Jueces 4:4–5.', ARRAY['Miriã','Hulda','Jael','Débora'], ARRAY['Miriam','Huldah','Jael','Deborah'], ARRAY['Miriam','Hulda','Jael','Débora'], 4),
('019f9752-0001-7000-8000-000000000050', 1, '019f9749-7a00-7000-8000-000000000001', 'Quem foi o primeiro rei de Israel?', 'Who was the first king of Israel?', '¿Quién fue el primer rey de Israel?', 'Saul foi ungido como o primeiro rei de Israel. Referência: 1 Samuel 10:1, 24.', 'Saul was anointed as the first king of Israel. Reference: 1 Samuel 10:1, 24.', 'Saúl fue ungido como el primer rey de Israel. Referencia: 1 Samuel 10:1, 24.', ARRAY['Davi','Saul','Salomão','Samuel'], ARRAY['David','Saul','Solomon','Samuel'], ARRAY['David','Saúl','Salomón','Samuel'], 2),
-- Nível 1 — Novo Testamento
('019f9752-0001-7000-8000-000000000051', 1, '019f9749-7a00-7000-8000-000000000002', 'Quem sou eu? Subi em um sicômoro para conseguir ver Jesus.', 'Who am I? I climbed a sycamore tree so I could see Jesus.', '¿Quién soy? Me subí a un sicómoro para poder ver a Jesús.', 'Zaqueu subiu em um sicômoro para ver Jesus passar. Referência: Lucas 19:2–4.', 'Zacchaeus climbed a sycamore tree to see Jesus pass by. Reference: Luke 19:2–4.', 'Zaqueo se subió a un sicómoro para ver pasar a Jesús. Referencia: Lucas 19:2–4.', ARRAY['Zaqueu','Bartimeu','Nicodemos','Jairo'], ARRAY['Zacchaeus','Bartimaeus','Nicodemus','Jairus'], ARRAY['Zaqueo','Bartimeo','Nicodemo','Jairo'], 1),
('019f9752-0001-7000-8000-000000000052', 1, '019f9749-7a00-7000-8000-000000000002', 'Qual discípulo disse que precisaria ver as marcas dos cravos para crer na ressurreição de Jesus?', 'Which disciple said he would need to see the nail marks to believe in Jesus'' resurrection?', '¿Qué discípulo dijo que necesitaría ver las marcas de los clavos para creer en la resurrección de Jesús?', 'Tomé expressou essa dúvida antes de ver Jesus ressuscitado. Referência: João 20:24–29.', 'Thomas expressed this doubt before seeing the risen Jesus. Reference: John 20:24–29.', 'Tomás expresó esta duda antes de ver a Jesús resucitado. Referencia: Juan 20:24–29.', ARRAY['André','Filipe','Tomé','Tiago'], ARRAY['Andrew','Philip','Thomas','James'], ARRAY['Andrés','Felipe','Tomás','Santiago'], 3),
('019f9752-0001-7000-8000-000000000053', 1, '019f9749-7a00-7000-8000-000000000002', 'Quem foi obrigado pelos soldados a carregar a cruz de Jesus?', 'Who was compelled by the soldiers to carry Jesus'' cross?', '¿Quién fue obligado por los soldados a llevar la cruz de Jesús?', 'Simão de Cirene foi obrigado a carregar a cruz atrás de Jesus. Referência: Lucas 23:26.', 'Simon of Cyrene was compelled to carry the cross behind Jesus. Reference: Luke 23:26.', 'Simón de Cirene fue obligado a llevar la cruz detrás de Jesús. Referencia: Lucas 23:26.', ARRAY['Simão Pedro','Simão, o Zelote','Simão de Cirene','Judas Tadeu'], ARRAY['Simon Peter','Simon the Zealot','Simon of Cyrene','Jude Thaddeus'], ARRAY['Simón Pedro','Simón el Zelote','Simón de Cirene','Judas Tadeo'], 3),
('019f9752-0001-7000-8000-000000000054', 1, '019f9749-7a00-7000-8000-000000000002', 'Qual discípulo pediu a Jesus: “Senhor, mostra-nos o Pai”?', 'Which disciple asked Jesus, “Lord, show us the Father”?', '¿Qué discípulo le pidió a Jesús: “Señor, muéstranos al Padre”?', 'Filipe fez esse pedido durante a conversa de Jesus com os discípulos. Referência: João 14:8–9.', 'Philip made this request during Jesus'' conversation with the disciples. Reference: John 14:8–9.', 'Felipe hizo esta petición durante la conversación de Jesús con los discípulos. Referencia: Juan 14:8–9.', ARRAY['Filipe','André','Mateus','Bartolomeu'], ARRAY['Philip','Andrew','Matthew','Bartholomew'], ARRAY['Felipe','Andrés','Mateo','Bartolomé'], 1),
('019f9752-0001-7000-8000-000000000055', 1, '019f9749-7a00-7000-8000-000000000002', 'Qual é o último livro da Bíblia?', 'What is the last book of the Bible?', '¿Cuál es el último libro de la Biblia?', 'Apocalipse é o último livro do cânon bíblico cristão. Referência: Apocalipse 1:1.', 'Revelation is the last book of the Christian biblical canon. Reference: Revelation 1:1.', 'Apocalipsis es el último libro del canon bíblico cristiano. Referencia: Apocalipsis 1:1.', ARRAY['Judas','Apocalipse','Atos','Malaquias'], ARRAY['Jude','Revelation','Acts','Malachi'], ARRAY['Judas','Apocalipsis','Hechos','Malaquías'], 2),
-- Nível 2 — Antigo Testamento
('019f9752-0002-7000-8000-000000000056', 2, '019f9749-7a00-7000-8000-000000000001', 'Qual era a função de Neemias na corte do rei Artaxerxes?', 'What was Nehemiah''s role in the court of King Artaxerxes?', '¿Cuál era la función de Nehemías en la corte del rey Artajerjes?', 'Neemias era copeiro do rei Artaxerxes. Referência: Neemias 1:11.', 'Nehemiah was cupbearer to King Artaxerxes. Reference: Nehemiah 1:11.', 'Nehemías era copero del rey Artajerjes. Referencia: Nehemías 1:11.', ARRAY['Escriba','Copeiro','General','Sacerdote'], ARRAY['Scribe','Cupbearer','General','Priest'], ARRAY['Escriba','Copero','General','Sacerdote'], 2),
('019f9752-0002-7000-8000-000000000057', 2, '019f9749-7a00-7000-8000-000000000001', 'Qual profeta pediu a Elias uma porção dobrada de seu espírito?', 'Which prophet asked Elijah for a double portion of his spirit?', '¿Qué profeta pidió a Elías una doble porción de su espíritu?', 'Eliseu pediu a Elias uma porção dobrada de seu espírito. Referência: 2 Reis 2:9–10.', 'Elisha asked Elijah for a double portion of his spirit. Reference: 2 Kings 2:9–10.', 'Eliseo le pidió a Elías una doble porción de su espíritu. Referencia: 2 Reyes 2:9–10.', ARRAY['Samuel','Eliseu','Isaías','Jonas'], ARRAY['Samuel','Elisha','Isaiah','Jonah'], ARRAY['Samuel','Eliseo','Isaías','Jonás'], 2),
('019f9752-0002-7000-8000-000000000058', 2, '019f9749-7a00-7000-8000-000000000001', 'Qual rei de Judá começou a reinar aos oito anos de idade?', 'Which king of Judah began to reign when he was eight years old?', '¿Qué rey de Judá comenzó a reinar a los ocho años?', 'Josias tinha oito anos quando começou a reinar em Judá. Referência: 2 Reis 22:1.', 'Josiah was eight years old when he began to reign in Judah. Reference: 2 Kings 22:1.', 'Josías tenía ocho años cuando comenzó a reinar en Judá. Referencia: 2 Reyes 22:1.', ARRAY['Ezequias','Manassés','Josias','Joás'], ARRAY['Hezekiah','Manasseh','Josiah','Joash'], ARRAY['Ezequías','Manasés','Josías','Joás'], 3),
('019f9752-0002-7000-8000-000000000059', 2, '019f9749-7a00-7000-8000-000000000001', 'Qual comandante do exército de Davi matou Absalão?', 'Which commander of David''s army killed Absalom?', '¿Qué comandante del ejército de David mató a Absalón?', 'Joabe matou Absalão durante a fuga do filho de Davi. Referência: 2 Samuel 18:14–15.', 'Joab killed Absalom during David''s son''s flight. Reference: 2 Samuel 18:14–15.', 'Joab mató a Absalón durante la huida del hijo de David. Referencia: 2 Samuel 18:14–15.', ARRAY['Abner','Amasa','Benaia','Joabe'], ARRAY['Abner','Amasa','Benaiah','Joab'], ARRAY['Abner','Amasa','Benaía','Joab'], 4),
('019f9752-0002-7000-8000-000000000060', 2, '019f9749-7a00-7000-8000-000000000001', 'Quem sou eu? Fui filha de Saul e esposa de Davi.', 'Who am I? I was Saul''s daughter and David''s wife.', '¿Quién soy? Fui hija de Saúl y esposa de David.', 'Mical, filha de Saul, tornou-se esposa de Davi. Referência: 1 Samuel 18:27.', 'Michal, Saul''s daughter, became David''s wife. Reference: 1 Samuel 18:27.', 'Mical, hija de Saúl, se convirtió en esposa de David. Referencia: 1 Samuel 18:27.', ARRAY['Abigail','Mical','Bate-Seba','Ainoã'], ARRAY['Abigail','Michal','Bathsheba','Ahinoam'], ARRAY['Abigaíl','Mical','Betsabé','Ahinoam'], 2),
-- Nível 2 — Novo Testamento
('019f9752-0002-7000-8000-000000000061', 2, '019f9749-7a00-7000-8000-000000000002', 'Quem sou eu? Sou um centurião romano, temente a Deus, que pediu que Pedro viesse à minha casa.', 'Who am I? I was a God-fearing Roman centurion who asked Peter to come to my house.', '¿Quién soy? Fui un centurión romano temeroso de Dios que pidió que Pedro fuera a mi casa.', 'Cornélio era um centurião romano que chamou Pedro à sua casa. Referência: Atos 10:1–5, 24–25.', 'Cornelius was a Roman centurion who summoned Peter to his house. Reference: Acts 10:1–5, 24–25.', 'Cornelio era un centurión romano que llamó a Pedro a su casa. Referencia: Hechos 10:1–5, 24–25.', ARRAY['Cornélio','Félix','Cláudio','Sérgio Paulo'], ARRAY['Cornelius','Felix','Claudius','Sergius Paulus'], ARRAY['Cornelio','Félix','Claudio','Sergio Paulo'], 1),
('019f9752-0002-7000-8000-000000000062', 2, '019f9749-7a00-7000-8000-000000000002', 'Qual jovem caiu de uma janela em Trôade enquanto Paulo falava e foi reanimado?', 'Which young man fell from a window in Troas while Paul was speaking and was restored to life?', '¿Qué joven cayó de una ventana en Troas mientras Pablo hablaba y fue reanimado?', 'Êutico caiu do terceiro andar durante uma longa mensagem de Paulo e foi reanimado. Referência: Atos 20:9–12.', 'Eutychus fell from the third story during Paul''s long message and was restored to life. Reference: Acts 20:9–12.', 'Eutico cayó del tercer piso durante un largo mensaje de Pablo y fue reanimado. Referencia: Hechos 20:9–12.', ARRAY['Tíquico','Êutico','Onésimo','Trófimo'], ARRAY['Tychicus','Eutychus','Onesimus','Trophimus'], ARRAY['Tíquico','Eutico','Onésimo','Trófimo'], 2),
('019f9752-0002-7000-8000-000000000063', 2, '019f9749-7a00-7000-8000-000000000002', 'Qual casal explicou a Apolo com mais exatidão o caminho de Deus?', 'Which couple explained the way of God more accurately to Apollos?', '¿Qué matrimonio explicó a Apolos con mayor exactitud el camino de Dios?', 'Priscila e Áquila instruíram Apolo com mais exatidão. Referência: Atos 18:24–26.', 'Priscilla and Aquila instructed Apollos more accurately. Reference: Acts 18:24–26.', 'Priscila y Aquila instruyeron a Apolos con mayor exactitud. Referencia: Hechos 18:24–26.', ARRAY['Ananias e Safira','Priscila e Áquila','José e Maria','Zacarias e Isabel'], ARRAY['Ananias and Sapphira','Priscilla and Aquila','Joseph and Mary','Zechariah and Elizabeth'], ARRAY['Ananías y Safira','Priscila y Aquila','José y María','Zacarías e Isabel'], 2),
('019f9752-0002-7000-8000-000000000064', 2, '019f9749-7a00-7000-8000-000000000002', 'Qual ofício Paulo exercia para ajudar em seu sustento?', 'What trade did Paul practice to help support himself?', '¿Qué oficio practicaba Pablo para ayudar a mantenerse?', 'Paulo trabalhava fazendo tendas. Referência: Atos 18:3.', 'Paul worked as a tentmaker. Reference: Acts 18:3.', 'Pablo trabajaba haciendo tiendas. Referencia: Hechos 18:3.', ARRAY['Pescador','Médico','Fabricante de tendas','Cobrador de impostos'], ARRAY['Fisherman','Physician','Tentmaker','Tax collector'], ARRAY['Pescador','Médico','Fabricante de tiendas','Recaudador de impuestos'], 3),
('019f9752-0002-7000-8000-000000000065', 2, '019f9749-7a00-7000-8000-000000000002', 'Em qual cidade os discípulos foram chamados cristãos pela primeira vez?', 'In which city were the disciples first called Christians?', '¿En qué ciudad fueron llamados cristianos los discípulos por primera vez?', 'Os discípulos foram chamados cristãos pela primeira vez em Antioquia. Referência: Atos 11:26.', 'The disciples were first called Christians in Antioch. Reference: Acts 11:26.', 'A los discípulos se les llamó cristianos por primera vez en Antioquía. Referencia: Hechos 11:26.', ARRAY['Éfeso','Antioquia','Corinto','Filipos'], ARRAY['Ephesus','Antioch','Corinth','Philippi'], ARRAY['Éfeso','Antioquía','Corinto','Filipos'], 2),
-- Nível 3 — Antigo Testamento
('019f9752-0003-7000-8000-000000000066', 3, '019f9749-7a00-7000-8000-000000000001', 'Qual profetisa foi consultada quando o Livro da Lei foi encontrado no templo durante o reinado de Josias?', 'Which prophetess was consulted when the Book of the Law was found in the temple during Josiah''s reign?', '¿Qué profetisa fue consultada cuando se encontró el Libro de la Ley en el templo durante el reinado de Josías?', 'Hulda foi a profetisa consultada pelos enviados do rei Josias. Referência: 2 Reis 22:14–20.', 'Huldah was the prophetess consulted by the envoys of King Josiah. Reference: 2 Kings 22:14–20.', 'Hulda fue la profetisa consultada por los enviados del rey Josías. Referencia: 2 Reyes 22:14–20.', ARRAY['Débora','Hulda','Noadias','Miriã'], ARRAY['Deborah','Huldah','Noadiah','Miriam'], ARRAY['Débora','Hulda','Noadías','Miriam'], 2),
('019f9752-0003-7000-8000-000000000067', 3, '019f9749-7a00-7000-8000-000000000001', 'Qual rei de Judá foi ferido com lepra após tentar queimar incenso no templo?', 'Which king of Judah was struck with leprosy after trying to burn incense in the temple?', '¿Qué rey de Judá fue herido con lepra después de intentar quemar incienso en el templo?', 'Uzias foi ferido com lepra ao agir presunçosamente no templo. Referência: 2 Crônicas 26:16–21.', 'Uzziah was struck with leprosy after acting presumptuously in the temple. Reference: 2 Chronicles 26:16–21.', 'Uzías fue herido con lepra al actuar con presunción en el templo. Referencia: 2 Crónicas 26:16–21.', ARRAY['Acaz','Uzias','Ezequias','Josias'], ARRAY['Ahaz','Uzziah','Hezekiah','Josiah'], ARRAY['Acaz','Uzías','Ezequías','Josías'], 2),
('019f9752-0003-7000-8000-000000000068', 3, '019f9749-7a00-7000-8000-000000000001', 'Qual escriba escreveu em um rolo as palavras ditadas pelo profeta Jeremias?', 'Which scribe wrote on a scroll the words dictated by the prophet Jeremiah?', '¿Qué escriba escribió en un rollo las palabras dictadas por el profeta Jeremías?', 'Baruque escreveu em um rolo todas as palavras que Jeremias lhe ditou. Referência: Jeremias 36:4.', 'Baruch wrote on a scroll all the words that Jeremiah dictated to him. Reference: Jeremiah 36:4.', 'Baruc escribió en un rollo todas las palabras que Jeremías le dictó. Referencia: Jeremías 36:4.', ARRAY['Esdras','Baruque','Seraías','Gemarias'], ARRAY['Ezra','Baruch','Seraiah','Gemariah'], ARRAY['Esdras','Baruc','Seraías','Gemarías'], 2),
('019f9752-0003-7000-8000-000000000069', 3, '019f9749-7a00-7000-8000-000000000001', 'Qual rei de Israel reinou apenas sete dias em Tirza?', 'Which king of Israel reigned only seven days in Tirzah?', '¿Qué rey de Israel reinó solamente siete días en Tirsa?', 'Zinri reinou em Tirza durante sete dias. Referência: 1 Reis 16:15–18.', 'Zimri reigned in Tirzah for seven days. Reference: 1 Kings 16:15–18.', 'Zimri reinó en Tirsa durante siete días. Referencia: 1 Reyes 16:15–18.', ARRAY['Onri','Zinri','Baasa','Elá'], ARRAY['Omri','Zimri','Baasha','Elah'], ARRAY['Omri','Zimri','Baasa','Ela'], 2),
('019f9752-0003-7000-8000-000000000070', 3, '019f9749-7a00-7000-8000-000000000001', 'Quem sou eu? Fui boiadeiro e cultivador de sicômoros antes de ser enviado para profetizar a Israel.', 'Who am I? I was a shepherd and a dresser of sycamore trees before being sent to prophesy to Israel.', '¿Quién soy? Fui pastor y cultivador de sicómoros antes de ser enviado a profetizar a Israel.', 'Amós declarou que era boiadeiro e cultivador de sicômoros antes de ser chamado por Deus. Referência: Amós 7:14–15.', 'Amos said he was a shepherd and a dresser of sycamore trees before God called him. Reference: Amos 7:14–15.', 'Amós declaró que era pastor y cultivador de sicómoros antes de ser llamado por Dios. Referencia: Amós 7:14–15.', ARRAY['Amós','Miqueias','Ageu','Sofonias'], ARRAY['Amos','Micah','Haggai','Zephaniah'], ARRAY['Amós','Miqueas','Hageo','Sofonías'], 1),
-- Nível 3 — Novo Testamento
('019f9752-0003-7000-8000-000000000071', 3, '019f9749-7a00-7000-8000-000000000002', 'Qual homem escreveu a Carta aos Romanos sob o ditado de Paulo?', 'Which man wrote the Letter to the Romans as Paul''s amanuensis?', '¿Qué hombre escribió la Carta a los Romanos al dictado de Pablo?', 'Tércio se identificou como aquele que escreveu a carta aos Romanos. Referência: Romanos 16:22.', 'Tertius identified himself as the one who wrote the letter to the Romans. Reference: Romans 16:22.', 'Tercio se identificó como quien escribió la carta a los Romanos. Referencia: Romanos 16:22.', ARRAY['Tito','Tércio','Timóteo','Tíquico'], ARRAY['Titus','Tertius','Timothy','Tychicus'], ARRAY['Tito','Tercio','Timoteo','Tíquico'], 2),
('019f9752-0003-7000-8000-000000000072', 3, '019f9749-7a00-7000-8000-000000000002', 'Quem Paulo deixou em Creta para colocar em ordem o que ainda faltava e estabelecer presbíteros?', 'Whom did Paul leave in Crete to set in order what remained and appoint elders?', '¿A quién dejó Pablo en Creta para poner en orden lo que faltaba y establecer ancianos?', 'Paulo deixou Tito em Creta com essa missão. Referência: Tito 1:5.', 'Paul left Titus in Crete with this mission. Reference: Titus 1:5.', 'Pablo dejó a Tito en Creta con esta misión. Referencia: Tito 1:5.', ARRAY['Tito','Silas','Timóteo','Lucas'], ARRAY['Titus','Silas','Timothy','Luke'], ARRAY['Tito','Silas','Timoteo','Lucas'], 1),
('019f9752-0003-7000-8000-000000000073', 3, '019f9749-7a00-7000-8000-000000000002', 'De qual cidade era natural Apolo, homem eloquente e poderoso nas Escrituras?', 'From which city was Apollos, an eloquent man mighty in the Scriptures, a native?', '¿De qué ciudad era natural Apolos, hombre elocuente y poderoso en las Escrituras?', 'Apolo era natural de Alexandria, no Egito. Referência: Atos 18:24.', 'Apollos was a native of Alexandria, Egypt. Reference: Acts 18:24.', 'Apolos era natural de Alejandría, en Egipto. Referencia: Hechos 18:24.', ARRAY['Antioquia','Alexandria','Tarso','Jerusalém'], ARRAY['Antioch','Alexandria','Tarsus','Jerusalem'], ARRAY['Antioquía','Alejandría','Tarso','Jerusalén'], 2),
('019f9752-0003-7000-8000-000000000074', 3, '019f9749-7a00-7000-8000-000000000002', 'Qual dos apóstolos era chamado de “o Zelote”?', 'Which of the apostles was called “the Zealot”?', '¿Cuál de los apóstoles era llamado “el Zelote”?', 'Simão era identificado entre os apóstolos como “o Zelote”. Referência: Lucas 6:15.', 'Simon was identified among the apostles as “the Zealot.” Reference: Luke 6:15.', 'Simón era identificado entre los apóstoles como “el Zelote”. Referencia: Lucas 6:15.', ARRAY['Simão Pedro','Simão, o Zelote','Judas Iscariotes','Tiago, filho de Zebedeu'], ARRAY['Simon Peter','Simon the Zealot','Judas Iscariot','James, son of Zebedee'], ARRAY['Simón Pedro','Simón el Zelote','Judas Iscariote','Santiago, hijo de Zebedeo'], 2),
('019f9752-0003-7000-8000-000000000075', 3, '019f9749-7a00-7000-8000-000000000002', 'Qual mulher é apresentada por Paulo como serva da igreja de Cencreia?', 'Which woman is presented by Paul as a servant of the church in Cenchreae?', '¿Qué mujer es presentada por Pablo como sierva de la iglesia de Cencrea?', 'Febe é apresentada por Paulo como serva da igreja de Cencreia. Referência: Romanos 16:1–2.', 'Phoebe is presented by Paul as a servant of the church in Cenchreae. Reference: Romans 16:1–2.', 'Febe es presentada por Pablo como sierva de la iglesia de Cencrea. Referencia: Romanos 16:1–2.', ARRAY['Júnia','Febe','Lídia','Dâmaris'], ARRAY['Junia','Phoebe','Lydia','Damaris'], ARRAY['Junia','Febe','Lidia','Damaris'], 2);

INSERT INTO questions (id, difficulty_level, category_id, status, created_by_user_id)
SELECT question_id, difficulty_level, category_id, 'DRAFT', '019f9749-5ada-702d-93ca-15664a51cd6a'
FROM biblical_question_seed_part_3
ON CONFLICT (id) DO UPDATE SET difficulty_level = EXCLUDED.difficulty_level, category_id = EXCLUDED.category_id, updated_at = now();

INSERT INTO question_translations (question_id, language_code, statement, explanation)
SELECT seed.question_id, translation.language_code, translation.statement, translation.explanation
FROM biblical_question_seed_part_3 seed
CROSS JOIN LATERAL (VALUES
  ('pt-BR', seed.pt_statement, seed.pt_explanation),
  ('en', seed.en_statement, seed.en_explanation),
  ('es', seed.es_statement, seed.es_explanation)
) translation(language_code, statement, explanation)
ON CONFLICT (question_id, language_code) DO UPDATE
SET statement = EXCLUDED.statement, explanation = EXCLUDED.explanation;

INSERT INTO answer_options (question_id, position, is_correct)
SELECT seed.question_id, option.position::smallint, option.position = seed.correct_position
FROM biblical_question_seed_part_3 seed
CROSS JOIN LATERAL unnest(seed.pt_options) WITH ORDINALITY option(content, position)
ON CONFLICT (question_id, position) DO UPDATE SET is_correct = EXCLUDED.is_correct;

INSERT INTO answer_option_translations (answer_option_id, language_code, content)
SELECT answer_option.id, translation.language_code, translation.content
FROM biblical_question_seed_part_3 seed
JOIN answer_options answer_option ON answer_option.question_id = seed.question_id
CROSS JOIN LATERAL (VALUES
  ('pt-BR', seed.pt_options[answer_option.position]),
  ('en', seed.en_options[answer_option.position]),
  ('es', seed.es_options[answer_option.position])
) translation(language_code, content)
ON CONFLICT (answer_option_id, language_code) DO UPDATE SET content = EXCLUDED.content;

UPDATE questions question
SET status = 'PUBLISHED', published_at = COALESCE(question.published_at, now()), updated_at = now()
FROM biblical_question_seed_part_3 seed
WHERE question.id = seed.question_id;
