-- Segundo banco complementar do Show da Bíblia: 30 questões inéditas.
-- Mantém quatro alternativas, traduções pt-BR/en/es e três níveis de dificuldade.
-- IDs 019f9752-...000076 a ...000105, posteriores ao primeiro complemento.

CREATE TEMP TABLE biblical_question_seed_part_4 (
  question_id uuid PRIMARY KEY,
  difficulty_level smallint NOT NULL,
  category_id uuid NOT NULL,
  pt_statement text NOT NULL,
  en_statement text NOT NULL,
  es_statement text NOT NULL,
  pt_explanation text NOT NULL,
  en_explanation text NOT NULL,
  es_explanation text NOT NULL,
  pt_options text[] NOT NULL,
  en_options text[] NOT NULL,
  es_options text[] NOT NULL,
  correct_position smallint NOT NULL,
  CONSTRAINT biblical_question_seed_part_4_difficulty_valid
    CHECK (difficulty_level BETWEEN 1 AND 3),
  CONSTRAINT biblical_question_seed_part_4_correct_position_valid
    CHECK (correct_position BETWEEN 1 AND 4),
  CONSTRAINT biblical_question_seed_part_4_options_count_valid
    CHECK (
      cardinality(pt_options) = 4
      AND cardinality(en_options) = 4
      AND cardinality(es_options) = 4
    ),
  CONSTRAINT biblical_question_seed_part_4_texts_not_blank
    CHECK (
      btrim(pt_statement) <> ''
      AND btrim(en_statement) <> ''
      AND btrim(es_statement) <> ''
      AND btrim(pt_explanation) <> ''
      AND btrim(en_explanation) <> ''
      AND btrim(es_explanation) <> ''
    )
) ON COMMIT DROP;

INSERT INTO biblical_question_seed_part_4 VALUES
-- Nível 1 — Antigo Testamento
('019f9752-0001-7000-8000-000000000076', 1, '019f9749-7a00-7000-8000-000000000001', 'Quem sou eu? Olhei para trás ao fugir de Sodoma e me tornei uma estátua de sal.', 'Who am I? I looked back while fleeing Sodom and became a pillar of salt.', '¿Quién soy? Miré atrás mientras huía de Sodoma y me convertí en una estatua de sal.', 'A mulher de Ló olhou para trás e tornou-se uma estátua de sal. Referência: Gênesis 19:26.', 'Lot''s wife looked back and became a pillar of salt. Reference: Genesis 19:26.', 'La mujer de Lot miró atrás y se convirtió en una estatua de sal. Referencia: Génesis 19:26.', ARRAY['A mulher de Ló','Raquel','Mical','Agar'], ARRAY['Lot''s wife','Rachel','Michal','Hagar'], ARRAY['La mujer de Lot','Raquel','Mical','Agar'], 1),
('019f9752-0001-7000-8000-000000000077', 1, '019f9749-7a00-7000-8000-000000000001', 'Qual rainha visitou Salomão para provar sua sabedoria com perguntas difíceis?', 'Which queen visited Solomon to test his wisdom with difficult questions?', '¿Qué reina visitó a Salomón para probar su sabiduría con preguntas difíciles?', 'A rainha de Sabá visitou Salomão e o provou com perguntas difíceis. Referência: 1 Reis 10:1–3.', 'The queen of Sheba visited Solomon and tested him with difficult questions. Reference: 1 Kings 10:1–3.', 'La reina de Sabá visitó a Salomón y lo probó con preguntas difíciles. Referencia: 1 Reyes 10:1–3.', ARRAY['Rainha de Sabá','Rainha Vasti','Rainha Ester','Rainha Atalia'], ARRAY['Queen of Sheba','Queen Vashti','Queen Esther','Queen Athaliah'], ARRAY['Reina de Sabá','Reina Vasti','Reina Ester','Reina Atalía'], 1),
('019f9752-0001-7000-8000-000000000078', 1, '019f9749-7a00-7000-8000-000000000001', 'Qual menino ouviu Deus chamá-lo durante a noite no tabernáculo?', 'Which boy heard God calling him during the night in the tabernacle?', '¿Qué niño escuchó a Dios llamarlo durante la noche en el tabernáculo?', 'Samuel ouviu o Senhor chamá-lo enquanto servia no tabernáculo. Referência: 1 Samuel 3:3–10.', 'Samuel heard the Lord calling him while he served in the tabernacle. Reference: 1 Samuel 3:3–10.', 'Samuel oyó al Señor llamarlo mientras servía en el tabernáculo. Referencia: 1 Samuel 3:3–10.', ARRAY['Samuel','Josias','Davi','Joás'], ARRAY['Samuel','Josiah','David','Joash'], ARRAY['Samuel','Josías','David','Joás'], 1),
('019f9752-0001-7000-8000-000000000079', 1, '019f9749-7a00-7000-8000-000000000001', 'De qual cidade Abraão saiu antes de seguir para Canaã?', 'From which city did Abraham leave before going toward Canaan?', '¿De qué ciudad salió Abraham antes de dirigirse a Canaán?', 'Abrão partiu de Ur dos caldeus com sua família antes de seguir para Canaã. Referência: Gênesis 11:31.', 'Abram departed from Ur of the Chaldeans with his family before going toward Canaan. Reference: Genesis 11:31.', 'Abram salió de Ur de los caldeos con su familia antes de dirigirse a Canaán. Referencia: Génesis 11:31.', ARRAY['Jericó','Ur dos caldeus','Nínive','Hebrom'], ARRAY['Jericho','Ur of the Chaldeans','Nineveh','Hebron'], ARRAY['Jericó','Ur de los caldeos','Nínive','Hebrón'], 2),
('019f9752-0001-7000-8000-000000000080', 1, '019f9749-7a00-7000-8000-000000000001', 'Qual instrumento Davi tocava para acalmar Saul?', 'Which instrument did David play to soothe Saul?', '¿Qué instrumento tocaba David para calmar a Saúl?', 'Davi tocava a harpa, e Saul se sentia aliviado. Referência: 1 Samuel 16:23.', 'David played the harp, and Saul felt relieved. Reference: 1 Samuel 16:23.', 'David tocaba el arpa y Saúl se sentía aliviado. Referencia: 1 Samuel 16:23.', ARRAY['Harpa','Flauta','Trombeta','Tambor'], ARRAY['Harp','Flute','Trumpet','Drum'], ARRAY['Arpa','Flauta','Trompeta','Tambor'], 1),
-- Nível 1 — Novo Testamento
('019f9752-0001-7000-8000-000000000081', 1, '019f9749-7a00-7000-8000-000000000002', 'Quem visitou Jesus à noite e ouviu que era necessário nascer de novo?', 'Who visited Jesus at night and heard that it was necessary to be born again?', '¿Quién visitó a Jesús de noche y oyó que era necesario nacer de nuevo?', 'Nicodemos foi a Jesus de noite e conversou com ele sobre o novo nascimento. Referência: João 3:1–7.', 'Nicodemus came to Jesus at night and spoke with him about new birth. Reference: John 3:1–7.', 'Nicodemo fue a Jesús de noche y conversó con él sobre el nuevo nacimiento. Referencia: Juan 3:1–7.', ARRAY['Nicodemos','Zaqueu','Jairo','Gamaliel'], ARRAY['Nicodemus','Zacchaeus','Jairus','Gamaliel'], ARRAY['Nicodemo','Zaqueo','Jairo','Gamaliel'], 1),
('019f9752-0001-7000-8000-000000000082', 1, '019f9749-7a00-7000-8000-000000000002', 'Qual mulher, também chamada Dorcas, foi ressuscitada por Pedro em Jope?', 'Which woman, also called Dorcas, was raised by Peter in Joppa?', '¿Qué mujer, también llamada Dorcas, fue resucitada por Pedro en Jope?', 'Tabita, também chamada Dorcas, foi ressuscitada por Pedro em Jope. Referência: Atos 9:36–41.', 'Tabitha, also called Dorcas, was raised by Peter in Joppa. Reference: Acts 9:36–41.', 'Tabita, también llamada Dorcas, fue resucitada por Pedro en Jope. Referencia: Hechos 9:36–41.', ARRAY['Marta','Tabita','Lídia','Priscila'], ARRAY['Martha','Tabitha','Lydia','Priscilla'], ARRAY['Marta','Tabita','Lidia','Priscila'], 2),
('019f9752-0001-7000-8000-000000000083', 1, '019f9749-7a00-7000-8000-000000000002', 'Em qual animal Jesus entrou em Jerusalém?', 'On what animal did Jesus enter Jerusalem?', '¿Sobre qué animal entró Jesús en Jerusalén?', 'Jesus entrou em Jerusalém montado em um jumentinho. Referência: Mateus 21:6–9.', 'Jesus entered Jerusalem riding on a young donkey. Reference: Matthew 21:6–9.', 'Jesús entró en Jerusalén montado en un burrito. Referencia: Mateo 21:6–9.', ARRAY['Cavalo','Camelo','Jumentinho','Cordeiro'], ARRAY['Horse','Camel','Young donkey','Lamb'], ARRAY['Caballo','Camello','Burrito','Cordero'], 3),
('019f9752-0001-7000-8000-000000000084', 1, '019f9749-7a00-7000-8000-000000000002', 'Em qual tanque Jesus curou um homem que estava enfermo havia trinta e oito anos?', 'At which pool did Jesus heal a man who had been ill for thirty-eight years?', '¿En qué estanque sanó Jesús a un hombre que había estado enfermo durante treinta y ocho años?', 'Jesus curou o homem enfermo no tanque de Betesda. Referência: João 5:2–9.', 'Jesus healed the sick man at the pool of Bethesda. Reference: John 5:2–9.', 'Jesús sanó al hombre enfermo en el estanque de Betesda. Referencia: Juan 5:2–9.', ARRAY['Siloé','Betesda','Samaria','Cafarnaum'], ARRAY['Siloam','Bethesda','Samaria','Capernaum'], ARRAY['Siloé','Betesda','Samaria','Capernaúm'], 2),
('019f9752-0001-7000-8000-000000000085', 1, '019f9749-7a00-7000-8000-000000000002', 'Quem sou eu? Sofria havia doze anos de uma hemorragia e fui curada ao tocar nas vestes de Jesus.', 'Who am I? I had suffered from bleeding for twelve years and was healed by touching Jesus'' clothes.', '¿Quién soy? Sufrí una hemorragia durante doce años y fui sanada al tocar las vestiduras de Jesús.', 'A mulher que sofria de hemorragia foi curada ao tocar nas vestes de Jesus. Referência: Marcos 5:25–34.', 'The woman who suffered from bleeding was healed when she touched Jesus'' clothes. Reference: Mark 5:25–34.', 'La mujer que sufría de hemorragia fue sanada al tocar las vestiduras de Jesús. Referencia: Marcos 5:25–34.', ARRAY['A mulher do fluxo de sangue','Maria Madalena','A filha de Jairo','Isabel'], ARRAY['The woman with the issue of blood','Mary Magdalene','Jairus'' daughter','Elizabeth'], ARRAY['La mujer del flujo de sangre','María Magdalena','La hija de Jairo','Isabel'], 1),
-- Nível 2 — Antigo Testamento
('019f9752-0002-7000-8000-000000000086', 2, '019f9749-7a00-7000-8000-000000000001', 'Qual mulher escondeu os espias israelitas em Jericó?', 'Which woman hid the Israelite spies in Jericho?', '¿Qué mujer escondió a los espías israelitas en Jericó?', 'Raabe escondeu os espias enviados por Josué em Jericó. Referência: Josué 2:1–6.', 'Rahab hid the spies sent by Joshua in Jericho. Reference: Joshua 2:1–6.', 'Rahab escondió a los espías enviados por Josué en Jericó. Referencia: Josué 2:1–6.', ARRAY['Raabe','Jael','Rute','Débora'], ARRAY['Rahab','Jael','Ruth','Deborah'], ARRAY['Rahab','Jael','Rut','Débora'], 1),
('019f9752-0002-7000-8000-000000000087', 2, '019f9749-7a00-7000-8000-000000000001', 'Além de Arão, quem sustentou uma das mãos de Moisés durante a batalha contra os amalequitas?', 'Besides Aaron, who held up one of Moses'' hands during the battle against the Amalekites?', 'Además de Aarón, ¿quién sostuvo una de las manos de Moisés durante la batalla contra los amalecitas?', 'Arão e Hur sustentaram as mãos de Moisés durante a batalha. Referência: Êxodo 17:10–12.', 'Aaron and Hur held up Moses'' hands during the battle. Reference: Exodus 17:10–12.', 'Aarón y Hur sostuvieron las manos de Moisés durante la batalla. Referencia: Éxodo 17:10–12.', ARRAY['Hur','Jetro','Calebe','Eleazar'], ARRAY['Hur','Jethro','Caleb','Eleazar'], ARRAY['Hur','Jetró','Caleb','Eleazar'], 1),
('019f9752-0002-7000-8000-000000000088', 2, '019f9749-7a00-7000-8000-000000000001', 'Qual filho de Saul era pai de Mefibosete?', 'Which son of Saul was the father of Mephibosheth?', '¿Qué hijo de Saúl era el padre de Mefiboset?', 'Jônatas, filho de Saul e amigo de Davi, era pai de Mefibosete. Referência: 2 Samuel 4:4.', 'Jonathan, Saul''s son and David''s friend, was Mephibosheth''s father. Reference: 2 Samuel 4:4.', 'Jonatán, hijo de Saúl y amigo de David, era el padre de Mefiboset. Referencia: 2 Samuel 4:4.', ARRAY['Absalão','Jônatas','Is-Bosete','Amnom'], ARRAY['Absalom','Jonathan','Ish-bosheth','Amnon'], ARRAY['Absalón','Jonatán','Is-boset','Amnón'], 2),
('019f9752-0002-7000-8000-000000000089', 2, '019f9749-7a00-7000-8000-000000000001', 'Qual juiz de Gileade teve trinta filhos que montavam em trinta jumentos?', 'Which judge of Gilead had thirty sons who rode on thirty donkeys?', '¿Qué juez de Galaad tuvo treinta hijos que montaban treinta asnos?', 'Jair teve trinta filhos que montavam em trinta jumentos. Referência: Juízes 10:3–4.', 'Jair had thirty sons who rode on thirty donkeys. Reference: Judges 10:3–4.', 'Jair tuvo treinta hijos que montaban treinta asnos. Referencia: Jueces 10:3–4.', ARRAY['Tola','Jair','Jefté','Ibsã'], ARRAY['Tola','Jair','Jephthah','Ibzan'], ARRAY['Tola','Jair','Jefté','Ibsán'], 2),
('019f9752-0002-7000-8000-000000000090', 2, '019f9749-7a00-7000-8000-000000000001', 'Qual rei de Judá se humilhou diante de Deus depois de ser levado cativo para a Babilônia?', 'Which king of Judah humbled himself before God after being taken captive to Babylon?', '¿Qué rey de Judá se humilló ante Dios después de ser llevado cautivo a Babilonia?', 'Manassés se humilhou diante de Deus após seu cativeiro. Referência: 2 Crônicas 33:10–13.', 'Manasseh humbled himself before God after his captivity. Reference: 2 Chronicles 33:10–13.', 'Manasés se humilló ante Dios después de su cautiverio. Referencia: 2 Crónicas 33:10–13.', ARRAY['Acaz','Manassés','Amon','Jeoaquim'], ARRAY['Ahaz','Manasseh','Amon','Jehoiakim'], ARRAY['Acaz','Manasés','Amón','Joacim'], 2),
-- Nível 2 — Novo Testamento
('019f9752-0002-7000-8000-000000000091', 2, '019f9749-7a00-7000-8000-000000000002', 'Quem foi o primeiro mártir cristão mencionado no livro de Atos?', 'Who was the first Christian martyr mentioned in the book of Acts?', '¿Quién fue el primer mártir cristiano mencionado en el libro de Hechos?', 'Estêvão foi apedrejado por seu testemunho de fé. Referência: Atos 7:54–60.', 'Stephen was stoned for his testimony of faith. Reference: Acts 7:54–60.', 'Esteban fue apedreado por su testimonio de fe. Referencia: Hechos 7:54–60.', ARRAY['Tiago','Estêvão','Barnabé','Filipe'], ARRAY['James','Stephen','Barnabas','Philip'], ARRAY['Santiago','Esteban','Bernabé','Felipe'], 2),
('019f9752-0002-7000-8000-000000000092', 2, '019f9749-7a00-7000-8000-000000000002', 'Qual discípulo de Damasco impôs as mãos sobre Saulo para que ele recuperasse a visão?', 'Which disciple in Damascus laid his hands on Saul so that he would regain his sight?', '¿Qué discípulo de Damasco impuso las manos sobre Saulo para que recuperara la vista?', 'Ananias foi enviado a Saulo para que ele recuperasse a visão. Referência: Atos 9:10–18.', 'Ananias was sent to Saul so that he would regain his sight. Reference: Acts 9:10–18.', 'Ananías fue enviado a Saulo para que recuperara la vista. Referencia: Hechos 9:10–18.', ARRAY['Ananias','Filipe','Barnabé','Silas'], ARRAY['Ananias','Philip','Barnabas','Silas'], ARRAY['Ananías','Felipe','Bernabé','Silas'], 1),
('019f9752-0002-7000-8000-000000000093', 2, '019f9749-7a00-7000-8000-000000000002', 'Em qual Evangelho está registrada a parábola do bom samaritano?', 'In which Gospel is the parable of the good Samaritan recorded?', '¿En qué Evangelio está registrada la parábola del buen samaritano?', 'A parábola do bom samaritano está registrada no Evangelho de Lucas. Referência: Lucas 10:25–37.', 'The parable of the good Samaritan is recorded in the Gospel of Luke. Reference: Luke 10:25–37.', 'La parábola del buen samaritano está registrada en el Evangelio de Lucas. Referencia: Lucas 10:25–37.', ARRAY['Mateus','Marcos','Lucas','João'], ARRAY['Matthew','Mark','Luke','John'], ARRAY['Mateo','Marcos','Lucas','Juan'], 3),
('019f9752-0002-7000-8000-000000000094', 2, '019f9749-7a00-7000-8000-000000000002', 'Em qual ilha Paulo chegou após um naufrágio?', 'On which island did Paul arrive after a shipwreck?', '¿En qué isla llegó Pablo después de un naufragio?', 'Após o naufrágio, Paulo e os demais chegaram à ilha de Malta. Referência: Atos 28:1.', 'After the shipwreck, Paul and the others arrived on the island of Malta. Reference: Acts 28:1.', 'Después del naufragio, Pablo y los demás llegaron a la isla de Malta. Referencia: Hechos 28:1.', ARRAY['Creta','Chipre','Malta','Patmos'], ARRAY['Crete','Cyprus','Malta','Patmos'], ARRAY['Creta','Chipre','Malta','Patmos'], 3),
('019f9752-0002-7000-8000-000000000095', 2, '019f9749-7a00-7000-8000-000000000002', 'Quem sou eu? Minha mãe era Eunice, minha avó era Loide, e recebi de Paulo importantes orientações.', 'Who am I? My mother was Eunice, my grandmother was Lois, and I received important instructions from Paul.', '¿Quién soy? Mi madre era Eunice, mi abuela era Loida y recibí importantes orientaciones de Pablo.', 'Timóteo recebeu uma fé sincera de sua mãe Eunice e de sua avó Loide. Referência: 2 Timóteo 1:5.', 'Timothy received a sincere faith from his mother Eunice and his grandmother Lois. Reference: 2 Timothy 1:5.', 'Timoteo recibió una fe sincera de su madre Eunice y de su abuela Loida. Referencia: 2 Timoteo 1:5.', ARRAY['Timóteo','Tito','Marcos','Onésimo'], ARRAY['Timothy','Titus','Mark','Onesimus'], ARRAY['Timoteo','Tito','Marcos','Onésimo'], 1),
-- Nível 3 — Antigo Testamento
('019f9752-0003-7000-8000-000000000096', 3, '019f9749-7a00-7000-8000-000000000001', 'Qual rei de Judá foi capturado pelos babilônios depois da queda de Jerusalém?', 'Which king of Judah was captured by the Babylonians after the fall of Jerusalem?', '¿Qué rey de Judá fue capturado por los babilonios después de la caída de Jerusalén?', 'Zedequias foi capturado após a queda de Jerusalém e levado à Babilônia. Referência: 2 Reis 25:1–7.', 'Zedekiah was captured after the fall of Jerusalem and taken to Babylon. Reference: 2 Kings 25:1–7.', 'Sedequías fue capturado después de la caída de Jerusalén y llevado a Babilonia. Referencia: 2 Reyes 25:1–7.', ARRAY['Jeoaquim','Zedequias','Ezequias','Josias'], ARRAY['Jehoiakim','Zedekiah','Hezekiah','Josiah'], ARRAY['Joacim','Sedequías','Ezequías','Josías'], 2),
('019f9752-0003-7000-8000-000000000097', 3, '019f9749-7a00-7000-8000-000000000001', 'Qual profeta teve uma visão do Senhor assentado em um alto e sublime trono, cercado por serafins?', 'Which prophet had a vision of the Lord seated on a high and exalted throne, surrounded by seraphim?', '¿Qué profeta tuvo una visión del Señor sentado en un trono alto y sublime, rodeado de serafines?', 'Isaías teve a visão do Senhor no templo, cercado por serafins. Referência: Isaías 6:1–3.', 'Isaiah had a vision of the Lord in the temple, surrounded by seraphim. Reference: Isaiah 6:1–3.', 'Isaías tuvo la visión del Señor en el templo, rodeado de serafines. Referencia: Isaías 6:1–3.', ARRAY['Ezequiel','Daniel','Isaías','Jeremias'], ARRAY['Ezekiel','Daniel','Isaiah','Jeremiah'], ARRAY['Ezequiel','Daniel','Isaías','Jeremías'], 3),
('019f9752-0003-7000-8000-000000000098', 3, '019f9749-7a00-7000-8000-000000000001', 'Qual cidade Onri comprou e tornou capital do reino de Israel?', 'Which city did Omri buy and make the capital of the kingdom of Israel?', '¿Qué ciudad compró Omri e hizo capital del reino de Israel?', 'Onri comprou o monte de Samaria e edificou ali a capital de Israel. Referência: 1 Reis 16:24.', 'Omri bought the hill of Samaria and built the capital of Israel there. Reference: 1 Kings 16:24.', 'Omri compró el monte de Samaria y edificó allí la capital de Israel. Referencia: 1 Reyes 16:24.', ARRAY['Siquém','Samaria','Jericó','Berseba'], ARRAY['Shechem','Samaria','Jericho','Beersheba'], ARRAY['Siquem','Samaria','Jericó','Beerseba'], 2),
('019f9752-0003-7000-8000-000000000099', 3, '019f9749-7a00-7000-8000-000000000001', 'Qual tribo de Israel não recebeu uma herança territorial como as demais tribos?', 'Which tribe of Israel did not receive a territorial inheritance like the other tribes?', '¿Qué tribu de Israel no recibió una herencia territorial como las demás tribus?', 'Os levitas não receberam uma herança territorial; o Senhor era a sua herança. Referência: Números 18:20–24.', 'The Levites did not receive a territorial inheritance; the Lord was their inheritance. Reference: Numbers 18:20–24.', 'Los levitas no recibieron una herencia territorial; el Señor era su herencia. Referencia: Números 18:20–24.', ARRAY['Benjamim','Levi','Judá','Efraim'], ARRAY['Benjamin','Levi','Judah','Ephraim'], ARRAY['Benjamín','Leví','Judá','Efraín'], 2),
('019f9752-0003-7000-8000-000000000100', 3, '019f9749-7a00-7000-8000-000000000001', 'Qual rei de Judá foi assassinado por seus próprios servos em sua casa?', 'Which king of Judah was assassinated by his own servants in his house?', '¿Qué rey de Judá fue asesinado por sus propios siervos en su casa?', 'Amon foi morto por seus próprios servos em sua casa. Referência: 2 Reis 21:23.', 'Amon was killed by his own servants in his house. Reference: 2 Kings 21:23.', 'Amón fue asesinado por sus propios siervos en su casa. Referencia: 2 Reyes 21:23.', ARRAY['Amon','Acaz','Jeoacaz','Uzias'], ARRAY['Amon','Ahaz','Jehoahaz','Uzziah'], ARRAY['Amón','Acaz','Joacaz','Uzías'], 1),
-- Nível 3 — Novo Testamento
('019f9752-0003-7000-8000-000000000101', 3, '019f9749-7a00-7000-8000-000000000002', 'Qual membro do Areópago creu após ouvir a pregação de Paulo em Atenas?', 'Which member of the Areopagus believed after hearing Paul preach in Athens?', '¿Qué miembro del Areópago creyó después de oír la predicación de Pablo en Atenas?', 'Dionísio, membro do Areópago, creu após ouvir Paulo em Atenas. Referência: Atos 17:34.', 'Dionysius, a member of the Areopagus, believed after hearing Paul in Athens. Reference: Acts 17:34.', 'Dionisio, miembro del Areópago, creyó después de escuchar a Pablo en Atenas. Referencia: Hechos 17:34.', ARRAY['Gamaliel','Dionísio','Félix','Sérgio Paulo'], ARRAY['Gamaliel','Dionysius','Felix','Sergius Paulus'], ARRAY['Gamaliel','Dionisio','Félix','Sergio Paulo'], 2),
('019f9752-0003-7000-8000-000000000102', 3, '019f9749-7a00-7000-8000-000000000002', 'Qual profeta anunciou uma grande fome e depois amarrou as próprias mãos e pés com o cinto de Paulo?', 'Which prophet announced a great famine and later bound his own hands and feet with Paul''s belt?', '¿Qué profeta anunció una gran hambre y después se ató las manos y los pies con el cinturón de Pablo?', 'Ágabo anunciou uma grande fome e profetizou sobre a prisão de Paulo. Referência: Atos 11:27–28; 21:10–11.', 'Agabus announced a great famine and prophesied about Paul''s imprisonment. Reference: Acts 11:27–28; 21:10–11.', 'Ágabo anunció una gran hambre y profetizó sobre el encarcelamiento de Pablo. Referencia: Hechos 11:27–28; 21:10–11.', ARRAY['Ágabo','Judas Barsabás','Silas','Menasom'], ARRAY['Agabus','Judas Barsabbas','Silas','Mnason'], ARRAY['Ágabo','Judas Barsabás','Silas','Mnasón'], 1),
('019f9752-0003-7000-8000-000000000103', 3, '019f9749-7a00-7000-8000-000000000002', 'Qual governador sucedeu Félix enquanto Paulo ainda estava preso?', 'Which governor succeeded Felix while Paul was still a prisoner?', '¿Qué gobernador sucedió a Félix mientras Pablo todavía estaba preso?', 'Pórcio Festo sucedeu Félix como governador. Referência: Atos 24:27.', 'Porcius Festus succeeded Felix as governor. Reference: Acts 24:27.', 'Porcio Festo sucedió a Félix como gobernador. Referencia: Hechos 24:27.', ARRAY['Gálio','Pórcio Festo','Herodes Agripa','Quirino'], ARRAY['Gallio','Porcius Festus','Herod Agrippa','Quirinius'], ARRAY['Galión','Porcio Festo','Herodes Agripa','Quirinio'], 2),
('019f9752-0003-7000-8000-000000000104', 3, '019f9749-7a00-7000-8000-000000000002', 'Qual discípulo era natural de Caná da Galileia?', 'Which disciple was a native of Cana in Galilee?', '¿Qué discípulo era natural de Caná de Galilea?', 'Natanael é identificado como sendo de Caná da Galileia. Referência: João 21:2.', 'Nathanael is identified as being from Cana in Galilee. Reference: John 21:2.', 'Natanael es identificado como natural de Caná de Galilea. Referencia: Juan 21:2.', ARRAY['Filipe','Natanael','Tomé','André'], ARRAY['Philip','Nathanael','Thomas','Andrew'], ARRAY['Felipe','Natanael','Tomás','Andrés'], 2),
('019f9752-0003-7000-8000-000000000105', 3, '019f9749-7a00-7000-8000-000000000002', 'Quem Paulo deixou doente em Mileto?', 'Whom did Paul leave sick in Miletus?', '¿A quién dejó Pablo enfermo en Mileto?', 'Paulo deixou Trófimo doente em Mileto. Referência: 2 Timóteo 4:20.', 'Paul left Trophimus sick in Miletus. Reference: 2 Timothy 4:20.', 'Pablo dejó enfermo a Trófimo en Mileto. Referencia: 2 Timoteo 4:20.', ARRAY['Onésimo','Trófimo','Tíquico','Aristarco'], ARRAY['Onesimus','Trophimus','Tychicus','Aristarchus'], ARRAY['Onésimo','Trófimo','Tíquico','Aristarco'], 2);

INSERT INTO questions (id, difficulty_level, category_id, status, created_by_user_id)
SELECT question_id, difficulty_level, category_id, 'DRAFT', '019f9749-5ada-702d-93ca-15664a51cd6a'
FROM biblical_question_seed_part_4
ON CONFLICT (id) DO UPDATE SET difficulty_level = EXCLUDED.difficulty_level, category_id = EXCLUDED.category_id, updated_at = now();

INSERT INTO question_translations (question_id, language_code, statement, explanation)
SELECT seed.question_id, translation.language_code, translation.statement, translation.explanation
FROM biblical_question_seed_part_4 seed
CROSS JOIN LATERAL (VALUES
  ('pt-BR', seed.pt_statement, seed.pt_explanation),
  ('en', seed.en_statement, seed.en_explanation),
  ('es', seed.es_statement, seed.es_explanation)
) translation(language_code, statement, explanation)
ON CONFLICT (question_id, language_code) DO UPDATE
SET statement = EXCLUDED.statement, explanation = EXCLUDED.explanation;

INSERT INTO answer_options (question_id, position, is_correct)
SELECT seed.question_id, option.position::smallint, option.position = seed.correct_position
FROM biblical_question_seed_part_4 seed
CROSS JOIN LATERAL unnest(seed.pt_options) WITH ORDINALITY option(content, position)
ON CONFLICT (question_id, position) DO UPDATE SET is_correct = EXCLUDED.is_correct;

INSERT INTO answer_option_translations (answer_option_id, language_code, content)
SELECT answer_option.id, translation.language_code, translation.content
FROM biblical_question_seed_part_4 seed
JOIN answer_options answer_option ON answer_option.question_id = seed.question_id
CROSS JOIN LATERAL (VALUES
  ('pt-BR', seed.pt_options[answer_option.position]),
  ('en', seed.en_options[answer_option.position]),
  ('es', seed.es_options[answer_option.position])
) translation(language_code, content)
ON CONFLICT (answer_option_id, language_code) DO UPDATE SET content = EXCLUDED.content;

UPDATE questions question
SET status = 'PUBLISHED', published_at = COALESCE(question.published_at, now()), updated_at = now()
FROM biblical_question_seed_part_4 seed
WHERE question.id = seed.question_id;
