<script setup lang="ts">
import { computed, onMounted } from 'vue';
import type { GameSummary } from '@/types/game';
import { formatDuration } from '@/utils/formatters';
import GameIcon from '@/components/game/GameIcon.vue';
const props = defineProps<{ summary: GameSummary; refreshUser: () => Promise<boolean> }>();
const emit = defineEmits<{ home: [] }>();
const cardsUsed = computed(() => props.summary.jokers.reduce((total, item) => total + item.quantityUsed, 0));
const usedJokers = computed(() => props.summary.jokers.filter((item) => item.quantityUsed > 0));
const challengeWon = computed(() => props.summary.endReason === 'COMPLETED' && props.summary.correctAnswers === 30 && props.summary.highestUnlockedLevel === 3);
onMounted(() => { void props.refreshUser(); });
</script>
<template><section class="page-content result-page"><div :class="['result-hero', { victory: challengeWon }]"><div v-if="challengeWon" class="celebration"><GameIcon name="celebration" /><GameIcon name="celebration" /><GameIcon name="celebration" /></div><div :class="['hero-icon', { victory: challengeWon }]"><GameIcon name="trophy" /></div><span v-if="challengeWon" class="victory-badge">{{ $t('challenge_victory_badge') }}</span><h1>{{ $t(challengeWon ? 'challenge_victory_title' : 'result_title') }}</h1><p>{{ $t(challengeWon ? 'challenge_victory_description' : 'result_description') }}</p><strong>{{ summary.score }}</strong><span class="score-label">{{ $t('game_score') }}</span></div><div class="result-metrics"><article><GameIcon name="correct" /><span>{{ $t('correct_answers') }}</span><strong>{{ summary.correctAnswers }}/30</strong></article><article><GameIcon name="time" /><span>{{ $t('time') }}</span><strong>{{ formatDuration(summary.durationSeconds) }}</strong></article><article><GameIcon name="items" /><span>{{ $t('items_used') }}</span><strong>{{ summary.skipsUsed + cardsUsed }}</strong></article><article><GameIcon name="level" /><span>{{ $t('unlocked_level') }}</span><strong>{{ summary.highestUnlockedLevel }}</strong></article></div><article class="data-card result-items"><h2>{{ $t('items_used') }}</h2><div><span>{{ $t('skips_used') }}</span><strong>{{ summary.skipsUsed }}</strong></div><div><span>{{ $t('cards_used') }}</span><strong>{{ cardsUsed }}</strong></div><div v-for="joker in usedJokers" :key="joker.code" class="joker-row"><span>{{ $t(joker.code === 'REVEAL_ANSWER' ? 'joker_reveal' : 'joker_eliminate') }}</span><strong>{{ joker.quantityUsed }}</strong></div><p v-if="!usedJokers.length" class="no-items">{{ $t('no_items_used') }}</p><v-btn color="primary" @click="emit('home')">{{ $t('back_home') }}</v-btn></article></section></template>
<style scoped>.result-page{max-width:900px}.result-hero{align-items:center;background:#f7e9d6;border:1px solid #7f4f24;border-radius:14px;display:grid;gap:.5rem;justify-items:center;padding:2rem;text-align:center}.result-hero.victory{background:#fff4cc;border:2px solid #d89b16}.celebration{align-items:center;color:#7f4f24;display:flex;gap:1rem}.hero-icon{align-items:center;background:#fff;border-radius:50%;color:#7f4f24;display:flex;height:56px;justify-content:center;width:56px}.hero-icon .game-icon{height:36px;width:36px}.hero-icon.victory{border:2px solid #d89b16;height:72px;width:72px}.hero-icon.victory .game-icon{height:46px;width:46px}.victory-badge{background:#7f4f24;border-radius:999px;color:#fff;font-size:.72rem;font-weight:900;letter-spacing:.08em;padding:6px 12px}.result-hero h1{font-size:1.7rem;margin:0}.result-hero p{color:#5d596c;margin:0;max-width:520px}.result-hero>strong{color:#7f4f24;font-size:3.5rem;line-height:1}.score-label,.result-metrics span{color:#797586}.result-metrics{display:grid;gap:.75rem;grid-template-columns:repeat(4,minmax(0,1fr));margin:1.25rem 0}.result-metrics article{align-items:center;background:#fff;border:1px solid #e7e5ef;border-radius:12px;display:grid;gap:4px;justify-items:center;padding:1rem;text-align:center}.result-metrics .game-icon{color:#7f4f24}.result-items{display:grid;gap:.75rem;padding:1.5rem}.result-items h2{margin:0}.result-items>div{display:flex;justify-content:space-between}.result-items>div span,.no-items{color:#797586}.joker-row{border-top:1px solid #e7e5ef;padding-top:.75rem}.result-items .v-btn{margin-top:.5rem}@media(max-width:700px){.result-metrics{grid-template-columns:repeat(2,minmax(0,1fr))}}</style>
